services:
  # create a SuperLink service
  superlink:
    image: flwr/superlink:${FLWR_VERSION:-1.22.0}
    command:
      - --insecure
      - --isolation
      - process
    ports:
      - 9093:9093
      # Add any ports from superexec-serverapp that need to be exposed
    networks:
      - flower-net

  # create a SuperExec service for SuperLink to execute ServerApps
  superexec-serverapp:
    privileged: true
    build:
      context: ${PROJECT_DIR:-.}
      dockerfile_inline: |
        FROM flwr/superexec:${FLWR_VERSION:-1.22.0}

        # gcc is required for the fastai quickstart example
        USER root
        # Set frontend to noninteractive to avoid prompts during tshark installation
        ENV DEBIAN_FRONTEND=noninteractive
        RUN apt-get update \
            && apt-get -y --no-install-recommends install \
            build-essential \
            tshark \
            linux-tools-common \
            linux-tools-generic \
            sysstat \
            nmon \
            && rm -rf /var/lib/apt/lists/*
        # USER app

        WORKDIR /app
        COPY --chown=app:app pyproject.toml .
        RUN sed -i 's/.*flwr\[simulation\].*//' pyproject.toml \
          && python -m pip install -U --no-cache-dir .

        ENTRYPOINT ["flower-superexec"]
    command:
      - --insecure
      - --plugin-type
      - serverapp
      - --appio-api-address
      - superlink:9091
    network_mode: "service:superlink"
    restart: on-failure:3
    depends_on:
      - superlink
    volumes:
      #remember to give the right writing and reading permission to ./server
      - ./server:/home

  # create two SuperNode services with different node configs
  supernode-1:
    image: flwr/supernode:${FLWR_VERSION:-1.22.0}
    command:
      - --insecure
      - --superlink
      - superlink:9092
      - --clientappio-api-address
      - 0.0.0.0:9094
      - --isolation
      - process
      - --node-config
      - "partition-id=0 num-partitions=2 dataset-path='/home/fashionmnist_part_1.npz'"
    depends_on:
      - superlink
    volumes:
      #remember to give the right writing and reading permission to ./client_1
      - ./client_1:/home
    networks:
      - flower-net

  supernode-2:
    image: flwr/supernode:${FLWR_VERSION:-1.22.0}
    command:
      - --insecure
      - --superlink
      - superlink:9092
      - --clientappio-api-address
      - 0.0.0.0:9095
      - --isolation
      - process
      - --node-config
      - "partition-id=1 num-partitions=2 dataset-path='/home/fashionmnist_part_2.npz'"
    depends_on:
      - superlink
    volumes:
      #remember to give the right writing and reading permission to ./client_2
      - ./client_2:/home
    networks:
      - flower-net

  # create one SuperExec service for each SuperNode to execute ClientApps
  superexec-clientapp-1:
    privileged: true
    build:
      context: ${PROJECT_DIR:-.}
      dockerfile_inline: |
        FROM flwr/superexec:${FLWR_VERSION:-1.22.0}

        # gcc is required for the fastai quickstart example
        USER root
        ENV DEBIAN_FRONTEND=noninteractive
        RUN apt-get update \
            && apt-get -y --no-install-recommends install \
            build-essential \
            linux-tools-common \
            linux-tools-generic \
            sysstat \
            nmon \
            && rm -rf /var/lib/apt/lists/*
        # USER app

        WORKDIR /app
        COPY --chown=app:app pyproject.toml .
        RUN sed -i 's/.*flwr\[simulation\].*//' pyproject.toml \
          && python -m pip install -U --no-cache-dir .

        ENTRYPOINT ["flower-superexec"]
    command:
      - --insecure
      - --plugin-type
      - clientapp
      - --appio-api-address
      - supernode-1:9094
    deploy:
      resources:
        limits:
          cpus: "4"
    stop_signal: SIGINT
    depends_on:
      - supernode-1
    volumes:
      #remember to give the right writing and reading permission to ./client_1
      - ./client_1:/home
    networks:
      - flower-net

  superexec-clientapp-2:
    privileged: true
    build:
      context: ${PROJECT_DIR:-.}
      dockerfile_inline: |
        FROM flwr/superexec:${FLWR_VERSION:-1.22.0}

        # gcc is required for the fastai quickstart example
        USER root
        ENV DEBIAN_FRONTEND=noninteractive
        RUN apt-get update \
            && apt-get -y --no-install-recommends install \
            build-essential \
            linux-tools-common \
            linux-tools-generic \
            sysstat \
            nmon \
            && rm -rf /var/lib/apt/lists/*
        # USER app

        WORKDIR /app
        COPY --chown=app:app pyproject.toml .
        RUN sed -i 's/.*flwr\[simulation\].*//' pyproject.toml \
          && python -m pip install -U --no-cache-dir .

        ENTRYPOINT ["flower-superexec"]
    command:
      - --insecure
      - --plugin-type
      - clientapp
      - --appio-api-address
      - supernode-2:9095
    deploy:
      resources:
        limits:
          cpus: "4"
    stop_signal: SIGINT
    depends_on:
      - supernode-2
    volumes:
      #remember to give the right writing and reading permission to ./client_2
      - ./client_2:/home
    networks:
      - flower-net

networks:
  flower-net:
